// Case studies — ordered by priority.
// Featured (id 1-3) are highlighted on the home page.

export const projectData = [
  {
    id: 1,
    slug: "paljai",
    title: "Paljai — Pet E-commerce / Marketplace Platform",
    image: "/image/project/Paljai/Screenshot 2026-01-09 153104.png",
    type: "image",
    tags: ["Next.js", "Supabase", "TailwindCSS"],
    role: "Frontend Developer",
    period: "2025 — Present",
    summary:
      "An e-commerce / marketplace platform for pets and pet-related products — with real users in production.",
    url: "",
    github: "",
    featured: true,
    images: [
      { src: "/image/project/Paljai/Screenshot 2026-01-09 153104.png", type: "image" },
      { src: "/image/project/Paljai/Screenshot 2026-01-09 153133.png", type: "image" },
      { src: "/image/project/Paljai/Screenshot 2026-01-09 153156.png", type: "image" },
    ],
    technologies: [
      { name: "Next.js", description: "React framework, App Router" },
      { name: "React", description: "UI library" },
      { name: "Supabase", description: "Auth, Storage, Postgres API" },
      { name: "TailwindCSS", description: "Styling system" },
      { name: "Vercel", description: "Deployment" },
    ],
    features: [
      "Frontend development for a pet & pet-product marketplace",
      "Seller Dashboard with product management",
      "Order & Stock UI flows",
      "Supabase integration: Auth, Storage, API",
      "Production UX/UI ownership and bug fixing",
    ],
    impact:
      "Live production platform with real sellers and buyers. Shipped features iteratively against startup-paced requirements.",
  },
  {
    id: 2,
    slug: "apower-erp",
    title: "Apower — ERP & Production Management",
    image: "/image/project/Apower/Screenshot 2026-03-19 151125.png",
    type: "image",
    tags: ["Vue 3", "TypeScript", "PHP", "MySQL"],
    role: "Full-stack Developer",
    period: "2024",
    summary:
      "A comprehensive ERP system for a manufacturing business — built around real factory operations.",
    url: "",
    github: "",
    featured: true,
    images: [
      { src: "/image/project/Apower/Screenshot 2026-03-19 151125.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-03-19 151141.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-03-19 151208.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-03-19 151216.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000618.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000632.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000644.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000652.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000713.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000726.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000732.png", type: "image" },
    ],
    technologies: [
      { name: "Vue 3", description: "Composition API" },
      { name: "TypeScript", description: "Type safety" },
      { name: "PHP", description: "Backend / REST API" },
      { name: "MySQL", description: "Relational database" },
      { name: "Docker", description: "Containerization" },
      { name: "VPS", description: "Self-hosted deployment" },
    ],
    features: [
      "Material Order & Purchase Request workflow",
      "Production Planning, Cutting, QC modules",
      "Stock management & inventory reports",
      "Worked with existing database & real business logic",
      "Requirement analysis & system flow design",
      "Database migration & VPS deployment",
    ],
    impact:
      "Replaced a paper-based workflow with a digital ERP. Tightened material → planning → QC → stock traceability end-to-end.",
  },
  {
    id: 3,
    slug: "freelance-business",
    title: "Freelance Business Web Applications",
    image: "/image/project/Nongnuch/Screenshot 2025-06-04 100000.png",
    type: "image",
    tags: ["React", "Vue 3", "PHP", "MySQL", "VPS"],
    role: "Freelance Developer · Full-stack",
    period: "2024 — Present",
    summary:
      "End-to-end web applications for SMB clients — sales systems, internal management tools, and tracking platforms.",
    url: "",
    github: "",
    featured: true,
    images: [
      { src: "/image/project/Nongnuch/Screenshot 2025-06-04 100000.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_11.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_12.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_13.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_14.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_15.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_16.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_17.png", type: "image" },
    ],
    technologies: [
      { name: "React / Vue 3", description: "Frontend (per project)" },
      { name: "PHP", description: "Backend API" },
      { name: "MySQL", description: "Database" },
      { name: "Supabase", description: "BaaS for select projects" },
      { name: "Docker", description: "Containerization" },
      { name: "VPS / Ubuntu", description: "Deployment" },
    ],
    features: [
      "Requirement gathering and system flow planning",
      "Database design from scratch or against existing schemas",
      "Frontend + backend development per client need",
      "Admin dashboards, order/sales systems, work tracking",
      "Deployment, domain/DNS setup, ongoing maintenance",
    ],
    impact:
      "Direct client engagements: I own the project from kickoff to deployment, including post-launch fixes.",
  },
  {
    id: 4,
    slug: "repair-request",
    title: "IT Repair Request System",
    image: "/image/project/project8.png",
    type: "image",
    tags: ["React", "PHP", "MySQL"],
    role: "Full-stack Developer",
    period: "2023",
    summary:
      "An internal ticketing system for IT support — request, track, and resolve repair work.",
    url: "",
    github: "",
    featured: false,
    images: [
      { src: "/image/project/project8.png", type: "image" },
    ],
    technologies: [
      { name: "React.js", description: "Frontend" },
      { name: "PHP", description: "Backend API" },
      { name: "MySQL", description: "Database" },
      { name: "AJAX", description: "Async polling for status updates" },
    ],
    features: [
      "User registration & authentication",
      "Submit repair request with details",
      "Admin dashboard for managing request status",
      "Realtime status polling for users",
      "Equipment & maintenance history tracking",
    ],
    impact:
      "Streamlined IT request handoff from informal chat messages to a tracked workflow.",
  },
  {
    id: 5,
    slug: "ai-loan-approval",
    title: "AI Loan Approval — Senior Project",
    image: "/image/project/project2.png",
    type: "image",
    tags: ["Machine Learning", "PHP", "MySQL"],
    role: "Solo · Academic",
    period: "2022",
    summary:
      "A web application that estimates real-estate loan approval likelihood using an ML training set.",
    url: "",
    github: "",
    featured: false,
    images: [
      { src: "/image/project/project2.png", type: "image" },
      { src: "/image/project/project3.png", type: "image" },
      { src: "/image/project/project4.png", type: "image" },
    ],
    technologies: [
      { name: "PHP", description: "Backend" },
      { name: "MySQL", description: "Database" },
      { name: "Machine Learning", description: "Training-set based approval" },
      { name: "Chart.js", description: "Data visualization" },
    ],
    features: [
      "Loan approval calculation from user profile data",
      "ML training set as decision criteria",
      "Comparison of loan conditions",
      "PDF report generation",
    ],
    impact:
      "Academic project — proof of concept for using historical loan data to score new applications.",
  },
  {
    id: 6,
    slug: "thread",
    title: "Thread — Social Discussion Platform",
    image: "/image/project/project5.png",
    type: "image",
    tags: ["Next.js", "MongoDB"],
    role: "Solo · Learning Build",
    period: "2023",
    summary:
      "A discussion thread platform built while learning the Next.js App Router and MongoDB stack.",
    url: "https://kratoo-nextjs.vercel.app/",
    github: "",
    featured: false,
    images: [
      { src: "/image/project/project5.png", type: "image" },
      { src: "/image/project/project5_10.png", type: "image" },
      { src: "/image/project/project5_11.png", type: "image" },
      { src: "/image/project/project5_12.png", type: "image" },
    ],
    technologies: [
      { name: "Next.js 13", description: "App Router" },
      { name: "MongoDB", description: "Database" },
      { name: "Mongoose", description: "ODM" },
      { name: "TailwindCSS", description: "Styling" },
      { name: "NextAuth.js", description: "Authentication" },
    ],
    features: [
      "Auth flow, post creation, comments, likes",
      "Thread search & notifications",
      "Responsive design",
    ],
    impact:
      "Personal learning project — hands-on practice with App Router and a full Next.js + MongoDB stack.",
  },
  {
    id: 7,
    slug: "real-estate",
    title: "Real Estate Listing Site",
    image: "/image/project/project6.png",
    type: "image",
    tags: ["Angular", "TypeScript", "REST API"],
    role: "Frontend · Bug Fix Engagement",
    period: "2023",
    summary:
      "Front-end engagement to resolve QA-reported bugs across the real-estate listing site.",
    url: "https://rakabaan.com/home",
    github: "",
    featured: false,
    images: [
      { src: "/image/project/project6.png", type: "image" },
      { src: "/image/project/project6_11.png", type: "image" },
      { src: "/image/project/project6_12.png", type: "image" },
    ],
    technologies: [
      { name: "Angular 15", description: "Frontend framework" },
      { name: "TypeScript", description: "Type safety" },
      { name: "RxJS", description: "Reactive programming" },
      { name: "REST API", description: "Backend integration" },
    ],
    features: [
      "Listing & search with filters",
      "Detail view with photo gallery",
      "Owner contact flow",
      "Listing management",
    ],
    impact:
      "Closed the QA bug list on filtering, detail views, and listing management.",
  },
  {
    id: 8,
    slug: "iot-smart-bin",
    title: "IoT Smart Trash Bin",
    image: "/image/project/test.mp4",
    type: "video",
    tags: ["IoT", "Arduino", "LINE Notify", "MySQL"],
    role: "Solo · Prototype",
    period: "2022",
    summary:
      "A hardware + software prototype: an IoT bin that reports fill level and pings LINE when full.",
    url: "",
    github: "",
    featured: false,
    images: [
      { src: "/image/project/test.mp4", type: "video" },
      { src: "/image/project/project1.png", type: "image" },
    ],
    technologies: [
      { name: "Arduino", description: "Microcontroller" },
      { name: "ESP32", description: "WiFi module" },
      { name: "Ultrasonic Sensor", description: "Distance detection" },
      { name: "LINE Notify", description: "Notification API" },
      { name: "MySQL", description: "Data storage" },
      { name: "PHP", description: "Backend API" },
    ],
    features: [
      "Automatic trash level detection",
      "LINE notifications when bin is full",
      "Database logging of events",
      "Web dashboard for remote monitoring",
    ],
    impact:
      "Hardware + software prototype that taught me end-to-end IoT integration.",
  },
];

export const featuredProjects = projectData.filter((p) => p.featured);
