// Case studies — ordered by priority (top 3 are featured)

export const projectData = [
  {
    id: 1,
    titleKey: "paljai",
    image: "/image/project/Paljai/Screenshot 2026-01-09 153104.png",
    type: "image",
    tags: ["Next.js", "Supabase", "TailwindCSS"],
    role: "Frontend Developer",
    url: "",
    github: "",
    images: [
      { src: "/image/project/Paljai/Screenshot 2026-01-09 153104.png", type: "image" },
      { src: "/image/project/Paljai/Screenshot 2026-01-09 153133.png", type: "image" },
      { src: "/image/project/Paljai/Screenshot 2026-01-09 153156.png", type: "image" },
    ],
    technologies: [
      { name: "Next.js", description: "React framework, SSR + App Router" },
      { name: "React", description: "UI library" },
      { name: "Supabase", description: "Auth, Storage, Postgres API" },
      { name: "TailwindCSS", description: "Styling system" },
      { name: "Vercel", description: "Deployment platform" },
    ],
    features: [
      "Frontend development for a pet & pet-product marketplace",
      "Seller Dashboard with product management",
      "Order & Stock UI flows",
      "Supabase integration: Auth, Storage, API",
      "Production UX/UI ownership and bug fixing",
    ],
  },
  {
    id: 2,
    titleKey: "apowerErp",
    image: "/image/project/Apower/Screenshot 2026-03-19 151125.png",
    type: "image",
    tags: ["Vue 3", "TypeScript", "PHP", "MySQL"],
    role: "Full-Stack Developer",
    url: "",
    github: "",
    images: [
      { src: "/image/project/Apower/Screenshot 2026-03-19 151125.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-03-19 151141.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-03-19 151208.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-03-19 151216.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000618.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000632.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000644.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000652.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000713.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000726.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000732.png", type: "image" },
    ],
    technologies: [
      { name: "Vue 3", description: "Frontend framework (Composition API)" },
      { name: "TypeScript", description: "Type safety" },
      { name: "PHP", description: "Backend / REST API" },
      { name: "MySQL", description: "Relational database" },
      { name: "Docker", description: "Containerization" },
      { name: "VPS", description: "Self-hosted deployment" },
    ],
    features: [
      "Material Order & Purchase Request workflow",
      "Production Planning, Cutting, QC modules",
      "Stock management & inventory reports",
      "Worked with existing database & real business logic",
      "Requirement analysis & system flow design",
      "Database migration & VPS deployment",
    ],
  },
  {
    id: 3,
    titleKey: "nongnuchSales",
    image: "/image/project/Nongnuch/Screenshot 2025-06-04 100000.png",
    type: "image",
    tags: ["Vue 3", "REST API", "Dashboard"],
    role: "Frontend Developer",
    url: "https://sales.nongnooch.app/login",
    github: "",
    images: [
      { src: "/image/project/Nongnuch/Screenshot 2025-06-04 100000.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_11.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_12.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_13.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_14.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_15.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_16.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_17.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_18.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_19.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_20.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_21.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_22.png", type: "image" },
    ],
    technologies: [
      { name: "Vue 3", description: "Frontend framework" },
      { name: "Composition API", description: "Modern Vue API" },
      { name: "REST API", description: "Backend integration" },
      { name: "Vuex", description: "State management" },
      { name: "Vue Router", description: "Client-side routing" },
      { name: "Axios", description: "HTTP client" },
    ],
    features: [
      "Sales data management for Nong Nooch Tropical Garden",
      "Quotation generation & approval flow",
      "Real-time sales tracking dashboard",
      "Customer database & history",
      "Automated alerts & notifications",
      "Reporting & analytics view",
    ],
  },
  {
    id: 4,
    titleKey: "repairRequest",
    image: "/image/project/project8.png",
    type: "image",
    tags: ["React", "PHP", "MySQL"],
    role: "Full-Stack Developer",
    url: "",
    github: "",
    images: [
      { src: "/image/project/project8.png", type: "image" },
    ],
    technologies: [
      { name: "React.js", description: "Frontend framework" },
      { name: "PHP", description: "Backend API" },
      { name: "MySQL", description: "Database" },
      { name: "AJAX", description: "Async polling for status updates" },
    ],
    features: [
      "User registration & authentication",
      "Submit repair request with details & attachments",
      "Admin dashboard for managing request status",
      "Realtime status polling for users",
      "Equipment & maintenance history tracking",
    ],
  },
  {
    id: 5,
    titleKey: "aiLoanApproval",
    image: "/image/project/project2.png",
    type: "image",
    tags: ["Machine Learning", "PHP", "MySQL"],
    role: "Solo Developer · Academic",
    url: "",
    github: "",
    images: [
      { src: "/image/project/project2.png", type: "image" },
      { src: "/image/project/project3.png", type: "image" },
      { src: "/image/project/project4.png", type: "image" },
    ],
    technologies: [
      { name: "PHP", description: "Backend language" },
      { name: "MySQL", description: "Database" },
      { name: "Machine Learning", description: "Training-set based approval" },
      { name: "Chart.js", description: "Data visualization" },
    ],
    features: [
      "Loan approval calculation from user profile data",
      "ML training set as decision criteria",
      "Comparison of loan conditions",
      "PDF report generation",
      "Senior thesis project",
    ],
  },
  {
    id: 6,
    titleKey: "threadProject",
    image: "/image/project/project5.png",
    type: "image",
    tags: ["Next.js", "MongoDB"],
    role: "Solo Developer · Learning",
    url: "https://kratoo-nextjs.vercel.app/",
    github: "",
    images: [
      { src: "/image/project/project5.png", type: "image" },
      { src: "/image/project/project5_10.png", type: "image" },
      { src: "/image/project/project5_11.png", type: "image" },
      { src: "/image/project/project5_12.png", type: "image" },
      { src: "/image/project/project5_13.png", type: "image" },
      { src: "/image/project/project5_14.png", type: "image" },
      { src: "/image/project/project5_15.png", type: "image" },
      { src: "/image/project/project5_16.png", type: "image" },
      { src: "/image/project/project5_17.png", type: "image" },
    ],
    technologies: [
      { name: "Next.js 13", description: "App Router, React framework" },
      { name: "MongoDB", description: "NoSQL database" },
      { name: "Mongoose", description: "MongoDB ODM" },
      { name: "Tailwind CSS", description: "Styling" },
      { name: "NextAuth.js", description: "Authentication" },
    ],
    features: [
      "Member system & login flow",
      "Create & edit thread posts",
      "Comment & like system",
      "Thread search",
      "Notifications",
      "Responsive design",
    ],
  },
  {
    id: 7,
    titleKey: "realEstateProject",
    image: "/image/project/project6.png",
    type: "image",
    tags: ["Angular", "TypeScript", "REST API"],
    role: "Frontend Developer · Bug Fixes",
    url: "https://rakabaan.com/home",
    github: "",
    images: [
      { src: "/image/project/project6.png", type: "image" },
      { src: "/image/project/project6_11.png", type: "image" },
      { src: "/image/project/project6_12.png", type: "image" },
      { src: "/image/project/project6_13.png", type: "image" },
      { src: "/image/project/project6_14.png", type: "image" },
    ],
    technologies: [
      { name: "Angular 15", description: "Frontend framework" },
      { name: "TypeScript", description: "Type safety" },
      { name: "RxJS", description: "Reactive programming" },
      { name: "Angular Material", description: "UI components" },
      { name: "REST API", description: "Backend integration" },
      { name: "NgRx", description: "State management" },
    ],
    features: [
      "Real estate listing & search",
      "Filter by type, price, location",
      "Detail view with photo gallery",
      "Owner contact flow",
      "Member system",
      "Listing management",
    ],
  },
  {
    id: 8,
    titleKey: "iotProject",
    image: "/image/project/test.mp4",
    type: "video",
    tags: ["IoT", "Arduino", "LINE Notify", "MySQL"],
    role: "Solo Developer · Prototype",
    url: "",
    github: "",
    images: [
      { src: "/image/project/test.mp4", type: "video" },
      { src: "/image/project/project1.png", type: "image" },
    ],
    technologies: [
      { name: "Arduino", description: "Microcontroller" },
      { name: "ESP32", description: "WiFi module" },
      { name: "Ultrasonic Sensor", description: "Distance detection" },
      { name: "LINE Notify", description: "Notification API" },
      { name: "MySQL", description: "Data storage" },
      { name: "PHP", description: "Backend API" },
    ],
    features: [
      "Smart trash bin prototype with IoT sensors",
      "Automatic trash level detection",
      "LINE notifications when bin is full",
      "Database logging of all events",
      "Usage statistics dashboard",
      "Web app for remote monitoring",
    ],
  },
];
