// Case studies — ordered by priority. Bilingual fields use { en, th } objects.

export const projectData = [
  {
    id: 1,
    slug: "paljai",
    title: {
      en: "Paljai — Pet E-commerce / Marketplace Platform",
      th: "Paljai — แพลตฟอร์ม E-commerce / Marketplace สัตว์เลี้ยง",
    },
    image: "/image/project/Paljai/Screenshot 2026-01-09 153104.png",
    type: "image",
    tags: ["React", "Express"],
    role: { en: "Frontend Developer", th: "Frontend Developer" },
    period: { en: "2025 — Present", th: "2025 — ปัจจุบัน" },
    summary: {
      en: "An e-commerce / marketplace platform for pets and pet-related products — with real users in production.",
      th: "แพลตฟอร์ม e-commerce / marketplace สำหรับสัตว์เลี้ยงและสินค้าเกี่ยวกับสัตว์เลี้ยง — มีผู้ใช้งานจริงบน production",
    },
    url: "",
    github: "",
    featured: true,
    images: [
      { src: "/image/project/Paljai/Screenshot 2026-01-09 153104.png", type: "image" },
      { src: "/image/project/Paljai/Screenshot 2026-01-09 153133.png", type: "image" },
      { src: "/image/project/Paljai/Screenshot 2026-01-09 153156.png", type: "image" },
    ],
    technologies: [
      { name: "React", description: { en: "Frontend UI", th: "Frontend UI" } },
      { name: "Express", description: { en: "Backend API", th: "Backend API" } },
    ],
    features: [
      { en: "Frontend development for a pet & pet-product marketplace", th: "พัฒนา frontend สำหรับ marketplace สัตว์เลี้ยงและสินค้าเกี่ยวกับสัตว์เลี้ยง" },
      { en: "Seller Dashboard with product management", th: "Seller Dashboard พร้อมระบบจัดการสินค้า" },
      { en: "Order & Stock UI flows", th: "UI flow สำหรับ Order และ Stock" },
      { en: "Supabase integration: Auth, Storage, API", th: "เชื่อม Supabase: Auth, Storage, API" },
      { en: "Production UX/UI ownership and bug fixing", th: "ดูแล UX/UI บน production และแก้บั๊ก" },
    ],
    impact: {
      en: "Live production platform with real sellers and buyers. Shipped features iteratively against startup-paced requirements.",
      th: "แพลตฟอร์มที่ใช้งานจริงบน production มีผู้ขายและผู้ซื้อจริง ส่งฟีเจอร์แบบ iterative ตาม requirement แบบ startup",
    },
  },
  {
    id: 2,
    slug: "apower-erp",
    title: {
      en: "Apower — ERP & Production Management",
      th: "Apower — ระบบ ERP สำหรับโรงงานผลิต",
    },
    image: "/image/project/Apower/Screenshot 2026-03-19 151125.png",
    type: "image",
    tags: ["React", "PHP"],
    role: { en: "Full-stack Developer", th: "Full-stack Developer" },
    period: { en: "2024", th: "2024" },
    summary: {
      en: "A comprehensive ERP system for a manufacturing business — built around real factory operations.",
      th: "ระบบ ERP ครบวงจรสำหรับธุรกิจผลิต — สร้างรอบ operation จริงของโรงงาน",
    },
    url: "",
    github: "",
    featured: true,
    images: [
      { src: "/image/project/Apower/Screenshot 2026-03-19 151125.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-03-19 151141.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-03-19 151208.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-03-19 151216.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000618.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000632.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000644.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000652.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000713.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000726.png", type: "image" },
      { src: "/image/project/Apower/Screenshot 2026-02-03 000732.png", type: "image" },
    ],
    technologies: [
      { name: "React", description: { en: "Frontend UI", th: "Frontend UI" } },
      { name: "PHP", description: { en: "Backend API", th: "Backend API" } },
    ],
    features: [
      { en: "Material Order & Purchase Request workflow", th: "Workflow ของ Material Order และ Purchase Request" },
      { en: "Production Planning, Cutting, QC modules", th: "โมดูล Production Planning, Cutting, QC" },
      { en: "Stock management & inventory reports", th: "จัดการ stock และรายงาน inventory" },
      { en: "Worked with existing database & real business logic", th: "ทำงานกับ database เดิมและ business logic จริง" },
      { en: "Requirement analysis & system flow design", th: "วิเคราะห์ requirement และออกแบบ flow ระบบ" },
      { en: "Database migration & VPS deployment", th: "ทำ database migration และ deploy ขึ้น VPS" },
    ],
    impact: {
      en: "Replaced a paper-based workflow with a digital ERP. Tightened material → planning → QC → stock traceability end-to-end.",
      th: "แทนที่ workflow แบบกระดาษด้วยระบบ ERP ดิจิทัล ทำให้ติดตาม material → planning → QC → stock ได้แบบครบวงจร",
    },
  },
  {
    id: 3,
    slug: "freelance-business",
    title: {
      en: "Freelance Business Web Applications",
      th: "เว็บแอปธุรกิจ — งาน Freelance",
    },
    image: "/image/project/Nongnuch/Screenshot 2025-06-04 100000.png",
    type: "image",
    tags: ["Vue 3", "Express"],
    role: {
      en: "Freelance Developer · Full-stack",
      th: "Freelance Developer · Full-stack",
    },
    period: { en: "2024 — Present", th: "2024 — ปัจจุบัน" },
    summary: {
      en: "End-to-end web applications for SMB clients — sales systems, internal management tools, and tracking platforms.",
      th: "เว็บแอปสำหรับลูกค้า SMB ครบวงจร — ระบบขาย, เครื่องมือจัดการภายใน และ platform ติดตามงาน",
    },
    url: "",
    github: "",
    featured: true,
    images: [
      { src: "/image/project/Nongnuch/Screenshot 2025-06-04 100000.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_11.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_12.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_13.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_14.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_15.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_16.png", type: "image" },
      { src: "/image/project/Nongnuch/project9_17.png", type: "image" },
    ],
    technologies: [
      { name: "Vue 3", description: { en: "Frontend UI", th: "Frontend UI" } },
      { name: "Express", description: { en: "Backend API", th: "Backend API" } },
    ],
    features: [
      { en: "Requirement gathering and system flow planning", th: "เก็บ requirement และวาง flow ระบบ" },
      { en: "Database design from scratch or against existing schemas", th: "ออกแบบ database ใหม่ หรือทำงานกับ schema เดิม" },
      { en: "Frontend + backend development per client need", th: "พัฒนา frontend + backend ตามความต้องการของลูกค้า" },
      { en: "Admin dashboards, order/sales systems, work tracking", th: "Admin dashboard, ระบบ order/sales, ระบบติดตามงาน" },
      { en: "Deployment, domain/DNS setup, ongoing maintenance", th: "Deploy, ตั้งค่าโดเมน/DNS และดูแลต่อเนื่อง" },
    ],
    impact: {
      en: "Direct client engagements: I own the project from kickoff to deployment, including post-launch fixes.",
      th: "ทำงานตรงกับลูกค้า — ดูแลโปรเจกต์ตั้งแต่ kickoff จนถึง deploy และแก้ไขหลัง launch",
    },
  },
  {
    id: 4,
    slug: "repair-request",
    title: {
      en: "IT Repair Request System",
      th: "ระบบแจ้งซ่อม IT",
    },
    image: "/image/project/project8.png",
    type: "image",
    tags: ["React", "PHP", "MySQL"],
    role: { en: "Full-stack Developer", th: "Full-stack Developer" },
    period: { en: "2023", th: "2023" },
    summary: {
      en: "An internal ticketing system for IT support — request, track, and resolve repair work.",
      th: "ระบบ ticketing ภายในสำหรับฝ่าย IT — แจ้ง ติดตาม และจัดการงานซ่อม",
    },
    url: "",
    github: "",
    featured: false,
    images: [
      { src: "/image/project/project8.png", type: "image" },
    ],
    technologies: [
      { name: "React.js", description: { en: "Frontend", th: "Frontend" } },
      { name: "PHP", description: { en: "Backend API", th: "Backend API" } },
      { name: "MySQL", description: { en: "Database", th: "Database" } },
      { name: "AJAX", description: { en: "Async polling for status", th: "Polling สถานะแบบ async" } },
    ],
    features: [
      { en: "User registration & authentication", th: "สมัครและเข้าสู่ระบบของผู้ใช้" },
      { en: "Submit repair request with details", th: "ส่งคำขอซ่อมพร้อมรายละเอียด" },
      { en: "Admin dashboard for managing request status", th: "Admin dashboard จัดการสถานะคำขอ" },
      { en: "Realtime status polling for users", th: "ผู้ใช้ดูสถานะแบบ realtime" },
      { en: "Equipment & maintenance history tracking", th: "ติดตามประวัติอุปกรณ์และการซ่อม" },
    ],
    impact: {
      en: "Streamlined IT request handoff from informal chat messages to a tracked workflow.",
      th: "ปรับการแจ้งงานซ่อม IT จากการคุยใน chat ให้กลายเป็น workflow ที่ติดตามได้",
    },
  },
  {
    id: 5,
    slug: "ai-loan-approval",
    title: {
      en: "AI Loan Approval — Senior Project",
      th: "AI Loan Approval — Senior Project",
    },
    image: "/image/project/project2.png",
    type: "image",
    tags: ["Machine Learning", "PHP", "MySQL"],
    role: { en: "Solo · Academic", th: "เดี่ยว · โปรเจกต์การศึกษา" },
    period: { en: "2022", th: "2022" },
    summary: {
      en: "A web application that estimates real-estate loan approval likelihood using an ML training set.",
      th: "เว็บแอปประเมินโอกาสอนุมัติสินเชื่ออสังหาริมทรัพย์โดยใช้ ML training set",
    },
    url: "",
    github: "",
    featured: false,
    images: [
      { src: "/image/project/project2.png", type: "image" },
      { src: "/image/project/project3.png", type: "image" },
      { src: "/image/project/project4.png", type: "image" },
    ],
    technologies: [
      { name: "PHP", description: { en: "Backend", th: "Backend" } },
      { name: "MySQL", description: { en: "Database", th: "Database" } },
      { name: "Machine Learning", description: { en: "Training-set based approval", th: "ใช้ training set ตัดสินผล" } },
      { name: "Chart.js", description: { en: "Data visualization", th: "การแสดงผลข้อมูล" } },
    ],
    features: [
      { en: "Loan approval calculation from user profile data", th: "คำนวณผลอนุมัติจากข้อมูลผู้ใช้" },
      { en: "ML training set as decision criteria", th: "ใช้ ML training set เป็นเกณฑ์ตัดสิน" },
      { en: "Comparison of loan conditions", th: "เปรียบเทียบเงื่อนไขสินเชื่อ" },
      { en: "PDF report generation", th: "ออกรายงาน PDF" },
    ],
    impact: {
      en: "Academic project — proof of concept for using historical loan data to score new applications.",
      th: "โปรเจกต์การศึกษา — พิสูจน์แนวคิดการใช้ข้อมูลสินเชื่อในอดีตเพื่อ score คำขอใหม่",
    },
  },
  {
    id: 6,
    slug: "thread",
    title: {
      en: "Thread — Social Discussion Platform",
      th: "Thread — แพลตฟอร์มกระทู้สังคม",
    },
    image: "/image/project/project5.png",
    type: "image",
    tags: ["Next.js", "MongoDB"],
    role: { en: "Solo · Learning Build", th: "เดี่ยว · ฝึกฝน" },
    period: { en: "2023", th: "2023" },
    summary: {
      en: "A discussion thread platform built while learning the Next.js App Router and MongoDB stack.",
      th: "แพลตฟอร์มกระทู้ที่ทำขึ้นระหว่างฝึก Next.js App Router และ MongoDB",
    },
    url: "https://kratoo-nextjs.vercel.app/",
    github: "",
    featured: false,
    images: [
      { src: "/image/project/project5.png", type: "image" },
      { src: "/image/project/project5_10.png", type: "image" },
      { src: "/image/project/project5_11.png", type: "image" },
      { src: "/image/project/project5_12.png", type: "image" },
    ],
    technologies: [
      { name: "Next.js 13", description: { en: "App Router", th: "App Router" } },
      { name: "MongoDB", description: { en: "Database", th: "Database" } },
      { name: "Mongoose", description: { en: "ODM", th: "ODM" } },
      { name: "TailwindCSS", description: { en: "Styling", th: "Styling" } },
      { name: "NextAuth.js", description: { en: "Authentication", th: "Authentication" } },
    ],
    features: [
      { en: "Auth flow, post creation, comments, likes", th: "ระบบ Auth, สร้างโพสต์, คอมเมนต์, ไลค์" },
      { en: "Thread search & notifications", th: "ค้นหากระทู้และแจ้งเตือน" },
      { en: "Responsive design", th: "Responsive ทุกอุปกรณ์" },
    ],
    impact: {
      en: "Personal learning project — hands-on practice with App Router and a full Next.js + MongoDB stack.",
      th: "โปรเจกต์ฝึกฝนส่วนตัว — ลงมือทำกับ App Router และ stack Next.js + MongoDB",
    },
  },
  {
    id: 7,
    slug: "real-estate",
    title: {
      en: "Real Estate Listing Site",
      th: "เว็บไซต์ประกาศอสังหาริมทรัพย์",
    },
    image: "/image/project/project6.png",
    type: "image",
    tags: ["Angular", "TypeScript", "REST API"],
    role: {
      en: "Frontend · Bug Fix Engagement",
      th: "Frontend · งานแก้บั๊ก",
    },
    period: { en: "2023", th: "2023" },
    summary: {
      en: "Front-end engagement to resolve QA-reported bugs across the real-estate listing site.",
      th: "งาน frontend แก้บั๊กที่ QA แจ้งบนเว็บไซต์ประกาศอสังหาริมทรัพย์",
    },
    url: "https://rakabaan.com/home",
    github: "",
    featured: false,
    images: [
      { src: "/image/project/project6.png", type: "image" },
      { src: "/image/project/project6_11.png", type: "image" },
      { src: "/image/project/project6_12.png", type: "image" },
    ],
    technologies: [
      { name: "Angular 15", description: { en: "Frontend framework", th: "Frontend framework" } },
      { name: "TypeScript", description: { en: "Type safety", th: "Type safety" } },
      { name: "RxJS", description: { en: "Reactive programming", th: "Reactive programming" } },
      { name: "REST API", description: { en: "Backend integration", th: "เชื่อมต่อ backend" } },
    ],
    features: [
      { en: "Listing & search with filters", th: "ระบบประกาศและค้นหาพร้อม filter" },
      { en: "Detail view with photo gallery", th: "หน้ารายละเอียดพร้อม gallery รูป" },
      { en: "Owner contact flow", th: "Flow ติดต่อเจ้าของ" },
      { en: "Listing management", th: "จัดการประกาศ" },
    ],
    impact: {
      en: "Closed the QA bug list on filtering, detail views, and listing management.",
      th: "ปิดลิสต์บั๊กที่ QA แจ้งในส่วน filter, รายละเอียด และจัดการประกาศ",
    },
  },
  {
    id: 8,
    slug: "iot-smart-bin",
    title: {
      en: "IoT Smart Trash Bin",
      th: "IoT — ถังขยะอัจฉริยะ",
    },
    image: "/image/project/test.mp4",
    type: "video",
    tags: ["IoT", "Arduino", "LINE Notify", "MySQL"],
    role: { en: "Solo · Prototype", th: "เดี่ยว · ต้นแบบ" },
    period: { en: "2022", th: "2022" },
    summary: {
      en: "A hardware + software prototype: an IoT bin that reports fill level and pings LINE when full.",
      th: "ต้นแบบ hardware + software — ถังขยะ IoT รายงานระดับขยะและแจ้งผ่าน LINE เมื่อเต็ม",
    },
    url: "",
    github: "",
    featured: false,
    images: [
      { src: "/image/project/test.mp4", type: "video" },
      { src: "/image/project/project1.png", type: "image" },
    ],
    technologies: [
      { name: "Arduino", description: { en: "Microcontroller", th: "Microcontroller" } },
      { name: "ESP32", description: { en: "WiFi module", th: "WiFi module" } },
      { name: "Ultrasonic Sensor", description: { en: "Distance detection", th: "ตรวจจับระยะ" } },
      { name: "LINE Notify", description: { en: "Notification API", th: "API แจ้งเตือน" } },
      { name: "MySQL", description: { en: "Data storage", th: "เก็บข้อมูล" } },
      { name: "PHP", description: { en: "Backend API", th: "Backend API" } },
    ],
    features: [
      { en: "Automatic trash level detection", th: "ตรวจจับระดับขยะอัตโนมัติ" },
      { en: "LINE notifications when bin is full", th: "แจ้งเตือนผ่าน LINE เมื่อเต็ม" },
      { en: "Database logging of events", th: "บันทึก event ลง database" },
      { en: "Web dashboard for remote monitoring", th: "Web dashboard ตรวจสอบจากระยะไกล" },
    ],
    impact: {
      en: "Hardware + software prototype that taught me end-to-end IoT integration.",
      th: "ต้นแบบ hardware + software ที่สอนผมเรื่อง IoT integration แบบครบวงจร",
    },
  },
];
